# -*- coding: utf-8 -*-
"""Skin_Disease_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFULC8TDrMeDqb2mGWZOgwCli5LGo46d

# Explainable Multi-Class Skin Disease Classification using Machine Learning

## Executive Summary

This project develops a machine learning system to classify six dermatological diseases using clinical symptom scores. Multiple algorithms were benchmarked using cross-validation, the best model was tuned, and predictions were interpreted using SHAP for transparency.

## Problem Statement

Accurate early diagnosis of skin diseases can improve treatment outcomes. This project evaluates whether machine learning can classify disease categories from structured clinical features.

## Objectives

- Compare multiple classification models
- Optimize best-performing model
- Evaluate generalization performance
- Explain predictions using SHAP
- Demonstrate single-patient prediction
- Prepare deployment-ready solution

## Data Analysis Report

1. **Dataset Overview**
*   Records : 366 patients
*   Attributes : 34 input features + 1 target feature
*   Target variable : class (6 skin disease catagories)
*   Feature Types :
    *   Clinical symptoms (erythema, itching, scaling, etc.)
    *   Histopathological findings (acanthosis, hyperkeratosis, Munro microabscess, etc.)
    *   Patient age
* Disease class:
  
    1. Psoriasis
    2. Seborrheic Dermatitis
    3. Lichen Planus
    4. Pityriasis Rosea
    5. Chronic Dermatities
    6. Pityriasis Rubra Pilaris

2. **Data Quality and Preprocessing**
*   Missing values contain only in attribute of Age(?) , replace with median imputer
*   No categorical encoding required
*   All symptom features are ordinal (0-3 scale)
*   Dataset is balanced enough for multiclass learning

## Import Required Libraries
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import joblib

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score,
    GridSearchCV,
    learning_curve
)

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

"""## Load Dataset"""

skin_df = pd.read_csv('dataset_35_dermatology.csv')

# Dataset overview

print("Shape:", skin_df.shape)

display(skin_df.head())

skin_df.describe().T

"""## Basic Cleaning"""

skin_df.columns = skin_df.columns.str.strip().str.replace(" ", "_")

# Replace ? with NaN if exists
skin_df = skin_df.replace("?", np.nan)

# Convert all columns to numeric where possible
for col in skin_df.columns:
  skin_df[col] = pd.to_numeric(skin_df[col], errors = "ignore")

# Target Column
TARGET = "class"

print("\nMissing Values:")
print(skin_df.isnull().sum().sort_values(ascending = False).head())

"""## Exploratory Data Analysis - EDA

Disease Class Mapping It's Easy To We Identify The Disease (For Report Purpose)
"""

disease_map = {
    1: "Psoriasis",
    2: "Seborrheic Dermatitis",
    3: "Lichen Planus",
    4: "Pityriasis Rosea",
    5: "Chronic Dermatitis",
    6: "Pityriasis Rubra Pilaris"
}

skin_df['Disease_Name'] = skin_df['class'].map(disease_map)
skin_df['Disease_Name']

# Target Distribution

plt.figure(figsize=(8, 4))
sns.countplot(x = skin_df["Disease_Name"])
plt.xticks(rotation = 45)
plt.title("Target Class Distribution")
plt.show()

"""## Insights

* The six disease classes are relatively balanced, with no extreme class imbalance.
* This is favorable for multiclass model training and reduces bias toward majority classes.
* Stratified train-test splitting is still recommended to preserve class proportions.
"""

# Missing Values

plt.figure(figsize=(10,4))
skin_df.isnull().sum().sort_values(ascending=False).plot(kind="bar")
plt.title("Missing Values by Feature")
plt.show()

"""## Insights

* Missing values are concentrated primarily in the Age feature.
* Most predictors are complete, indicating strong dataset quality.
* Median imputation is an appropriate strategy for handling missing Age values.
"""

# Feature Correlation

plt.figure(figsize=(10,8))
corr = skin_df.corr(numeric_only=True)
sns.heatmap(corr, cmap="coolwarm", center=0)
plt.title("Correlation Heatmap")
plt.show()

"""## Insights

* Several clinical and histopathological features show moderate positive relationships.
* Correlated symptoms may represent related disease manifestations.
* Tree-based models can handle correlated predictors effectively, while linear models may benefit from regularization.
"""

# Top feature variance
variance = skin_df.drop(columns=[TARGET, "Disease_Name"]).var().sort_values(ascending=False).head(15)

plt.figure(figsize=(6,4))
variance.plot(kind="bar")
plt.title("Top 15 High Variance Features")
plt.show()

"""## Insights

* High variance features exhibit stronger spread across patients and may provide better discriminatory power.
* These variables are likely useful for separating disease classes.
* Variance alone does not imply importance, so model-based feature evaluation is required.
"""

# Box plot
num_cols = skin_df.drop(columns=[TARGET, "Disease_Name"]).columns[:8]

skin_df[num_cols].plot(kind="box", subplots=True, layout=(2,4), figsize=(10, 7))
plt.tight_layout()
plt.show()

"""## Insights

* Several features show distinct distributions and mild outliers across observations.
* Outliers may represent severe symptom scores rather than data errors.
* Feature scaling helps standardize distributions for distance-based and linear models.

## Split Data
"""

x = skin_df.drop([TARGET, 'Disease_Name'], axis = 1)
y = skin_df[TARGET] - 1

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size = 0.2,
    stratify = y,
    random_state = 42
  )

"""## Pipeline Preprocessor"""

base_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy = "median")),
    ("scaler", StandardScaler())
])

"""## Model Building

**Baseline Models:**

1. **Logistic Regression:** Baseline comparison and Statistically interpretable.

**Tree-Based Models (Primary Models):**

2. **Random Forest:** High accuracy and robustness, Handles correlated features well, Resistant to noise and outliers, and Widely accepted in medical ML.

3. **XGBoost:** State-of-the-art performance and Suitable for research-level experiments.

**Distance-Based Models:**

4. **Support Vector Machine (SVM):** Strong performance on small datasets and Good margin maximization.


"""

models = {
    "Logistic Regression": LogisticRegression(multi_class = 'multinomial', class_weight = 'balanced', max_iter = 1000, random_state = 42),
    "Random Forest": RandomForestClassifier(class_weight = 'balanced', n_estimators = 300, random_state = 42),
    "XGBoost": XGBClassifier(objective = 'multi:softmax', num_class = 6, eval_metric = 'mlogloss', random_state = 42),
    "SVM": SVC(kernel = 'rbf', probability = True, class_weight = 'balanced'),
}

"""## Cross Validation Comparision"""

results = []

cv = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 42)

for name, model in models.items():

  pipe = Pipeline([
      ("imputer", SimpleImputer(strategy = "median")),
      ("scaler", StandardScaler()),
      ("model", model)
  ])

  scores = cross_val_score(
      pipe,
      x_train,
      y_train,
      cv = cv,
      scoring = "f1_weighted",
      n_jobs = -1
  )

  results.append({
      "Model": name,
      "CV Mean F1-weighted": scores.mean(),
      "CV Std": scores.std()
  })

results_df = pd.DataFrame(results).sort_values(
    by = "CV Mean F1-weighted",
    ascending = False
)

print("\nModel Comparision:")
display(results_df)

# visualize Model Scores

plt.figure(figsize=(10,5))
sns.barplot(
    data=results_df,
    x="CV Mean F1-weighted",
    y="Model"
)
plt.title("Cross Validation F1-weighted")
plt.show()

"""Final Model Selection:

* Although Logistic Regression and SVM achieved the highest weighted F1 score (0.9793), Logistic Regression was selected as the final model due to equivalent predictive performance with lower computational complexity and higher interpretability.

## Hyperparameter Tuning
"""

lr_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(multi_class = 'multinomial', class_weight = 'balanced', max_iter = 1000, random_state = 42))
])

param_grid = {
    "model__C": [0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10],
    "model__class_weight": [None, "balanced"],
    "model__solver": ["lbfgs", "liblinear"],
    "model__multi_class": ["ovr", "multinomial"]
}

grid = GridSearchCV(
    lr_pipe,
    param_grid=param_grid,
    cv=cv,
    scoring="f1_weighted",
    n_jobs=-1,
    verbose=1
)

grid.fit(x_train, y_train)

best_model = grid.best_estimator_

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

"""## Final Test Evaluation"""

y_pred = best_model.predict(x_test)

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="weighted")

print("\nTest Accuracy:", acc)
print("Weighted F1:", f1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

summary = pd.DataFrame({
    "Metric":["Accuracy","Weighted F1"],
    "Score":[acc,f1]
})
summary

"""* After hyperparameter optimization using GridSearchCV, Logistic Regression achieved a weighted F1-score of 0.9828 in cross-validation and 97.3% accuracy on the holdout test set. One-vs-Rest classification with C=10 delivered the best balance of performance and interpretability."""

# Confusion Matrix
plt.figure(figsize=(8,6))
sns.heatmap(
    confusion_matrix(y_test, y_pred),
    annot=True,
    fmt="d",
    cmap="Blues"
)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""## Insights

* Most disease classes were classified correctly, indicating strong predictive performance.
* Misclassifications are concentrated among clinically similar disease categories.
* This suggests the model captures major patterns but some overlap remains between related conditions.

## Learning Curves
Training vs Validation Accuracy vs Dataset Size
"""

train_sizes, train_scores, val_scores = learning_curve(
    estimator=best_model,
    X=x_train,
    y=y_train,
    cv=5,
    scoring="f1_weighted",
    train_sizes=np.linspace(0.1, 1.0, 8),
    n_jobs=-1,
    shuffle=True,
    random_state=42
)

train_mean = train_scores.mean(axis=1)
train_std  = train_scores.std(axis=1)

val_mean = val_scores.mean(axis=1)
val_std  = val_scores.std(axis=1)

plt.figure(figsize=(10,6))

plt.plot(train_sizes, train_mean, marker="o", label="Training F1-weighted")
plt.plot(train_sizes, val_mean, marker="s", label="Validation F1-weighted")

plt.fill_between(
    train_sizes,
    train_mean - train_std,
    train_mean + train_std,
    alpha=0.15
)

plt.fill_between(
    train_sizes,
    val_mean - val_std,
    val_mean + val_std,
    alpha=0.15
)

plt.title("Learning Curve")
plt.xlabel("Training Set Size")
plt.ylabel("F1-weighted Score")
plt.legend()
plt.grid(True)
plt.show()

"""## Insights

* Training and validation curves converge at a high score, indicating good generalization.
* The small gap between curves suggests limited overfitting.
* Performance gains from substantially more data may be incremental, though still beneficial.

## Feature Importance
"""

lr = best_model.named_steps["model"]

importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": np.mean(np.abs(lr.coef_), axis=0)
}).sort_values(by="Importance", ascending=False).head(15)

plt.figure(figsize=(10,6))
sns.barplot(data=importance, x="Importance", y="Feature")
plt.title("Top 15 Important Features (Logistic Regression Coefficients)")
plt.show()

"""## Insights

* A subset of symptoms contributes more strongly to prediction than others.
* These features may have higher clinical relevance for distinguishing disease classes.
* Important predictors can guide simplified screening tools and domain interpretation.

## SHAP Explainability
SHAP explains which symptoms most influenced predictions globally and for each patient.
"""

print("Generating SHAP values...")

X_train_processed = best_model.named_steps["imputer"].transform(x_train)
X_test_processed  = best_model.named_steps["imputer"].transform(x_test)

def predict_proba_wrapper(data):
    return lr.predict_proba(data)

explainer = shap.LinearExplainer(lr, shap.sample(X_train_processed, 100))

shap_values = explainer.shap_values(X_test_processed)

shap.summary_plot(
    shap_values,
    X_test_processed,
    feature_names=x.columns,
    class_names=[disease_map[i+1] for i in range(len(disease_map))] # Added class_names for clarity
)

"""## Insights

* SHAP confirms which features most strongly influence model predictions globally.
* Both feature magnitude and direction of impact vary across patients.
* This improves transparency and supports trust in healthcare-oriented ML systems.

## Missclassification Analysis
"""

errors = x_test.copy()
errors["Actual"] = y_test
errors["Predicted"] = y_pred
errors[errors["Actual"] != errors["Predicted"]].head(10)

"""## Save Model"""

# Save Model
joblib.dump(best_model, "skin_disease_model.pkl")
print("Model saved: skin_disease_model.pkl")

# Save Features List
joblib.dump(list(x.columns), "features.pkl")
print("Model Feature List saved: features.pkl")

"""## Single Patient Prediction Function
Input symptom scores -> disease class + confidence + top 3 reasons
"""

def predict_single_patient(
    symptom_scores: dict,
    model_path="skin_disease_model.pkl",
    feature_columns=None
):
    """
    Predict disease class for one patient and explain top reasons.

    Parameters
    ----------
    symptom_scores : dict
        Example:
        {
            "erythema": 2,
            "scaling": 3
        }

    model_path : str
        Saved trained model path.

    feature_columns : list
        Exact training feature order.
    """

    # Load model (this is the Pipeline)
    model = joblib.load(model_path)

    if feature_columns is None:
        raise ValueError("feature_columns must be provided.")

    # Create dataframe
    patient_df = pd.DataFrame([symptom_scores])

    # Ensure exact column order
    patient_df = patient_df.reindex(
        columns=feature_columns,
        fill_value=0
    )

    # Prediction
    pred_class = model.predict(patient_df)[0]
    pred_prob = model.predict_proba(patient_df)[0]

    confidence = float(np.max(pred_prob))

    # SHAP Explainer
    background_data = shap.sample(x_train, 100)
    explainer = shap.LinearExplainer(model.named_steps["model"], background_data)

    # Calculate SHAP values for the single patient (patient_df is the unprocessed input)
    shap_values = explainer.shap_values(patient_df)

    # Predicted class index
    class_index = int(pred_class)

    # multiclass shape handling
    if isinstance(shap_values, list):
        sv = shap_values[class_index][0]
    else:
        sv = shap_values[0, :, class_index]

    # Reason dataframe
    reason_df = pd.DataFrame({
        "Feature": feature_columns,
        "Value": patient_df.iloc[0].values,
        "Impact": sv,
        "AbsImpact": np.abs(sv)
    }).sort_values(
        by="AbsImpact",
        ascending=False
    )

    top3 = reason_df.head(3)[
        ["Feature", "Value", "Impact"]
    ]

    result = {
        "Predicted_Class": int(pred_class + 1),
        "Confidence": round(confidence, 4),
        "Top_3_Reasons": top3
    }

    return result

"""Example Patient Test"""

feature_columns = x.columns.tolist()

sample_patient = {col: 0 for col in feature_columns}

sample_patient[feature_columns[0]] = 3
sample_patient[feature_columns[1]] = 2
sample_patient[feature_columns[2]] = 1
sample_patient[feature_columns[3]] = 3

result = predict_single_patient(
    symptom_scores=sample_patient,
    model_path="skin_disease_model.pkl",
    feature_columns=feature_columns
)

print("Predicted Disease Class:", result["Predicted_Class"])
print("Confidence:", result["Confidence"])

print("\nTop 3 Reasons:")
display(result["Top_3_Reasons"])

"""Visual SHAP force plot for single patient"""

patient_df = pd.DataFrame([sample_patient]).reindex(columns=x.columns)
patient_processed = best_model.named_steps["imputer"].transform(patient_df)

shap_values = explainer.shap_values(patient_processed)

# Predicted_Class from the result is already 0-indexed
idx = result["Predicted_Class"]

if isinstance(shap_values, list):
    shap.force_plot(
        explainer.expected_value[idx],
        shap_values[idx][0],
        patient_processed[0],
        feature_names=x.columns,
        matplotlib=True
    )
else:
    shap.force_plot(
        explainer.expected_value[idx],
        shap_values[0, :, idx],
        patient_processed[0],
        feature_names=x.columns,
        matplotlib=True
    )

"""## Insights

* The prediction is driven by a combination of positive and negative feature contributions.
* Top contributing symptoms explain why the selected disease class was predicted.
* Patient-level explanations improve interpretability for real-world clinical use.

## Skills Demonstrated

- Machine Learning
- Cross Validation
- Hyperparameter Tuning
- Explainable AI (SHAP)
- Healthcare Analytics
- Deployment Readiness
- Python Production Workflow

## Conclusion
The final model achieved strong multiclass classification performance on dermatology data while maintaining interpretability. This demonstrates the practical potential of machine learning for clinical decision support systems.
"""